# Generated by Django 5.2.5 on 2025-08-13 22:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="tweet",
            name="mentions",
            field=models.ManyToManyField(
                blank=True,
                related_name="mentioned_in_tweets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
